{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework",
    "module": "spring-webmvc",
    "version": "6.1.11",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-aop",
          "version": {
            "requires": "6.1.11"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-beans",
          "version": {
            "requires": "6.1.11"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-context",
          "version": {
            "requires": "6.1.11"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "6.1.11"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-expression",
          "version": {
            "requires": "6.1.11"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-web",
          "version": {
            "requires": "6.1.11"
          }
        }
      ],
      "files": [
        {
          "name": "spring-webmvc-6.1.11.jar",
          "url": "spring-webmvc-6.1.11.jar",
          "size": 1046877,
          "sha512": "610888d2b0ff8727594c51b5362fce5dec4f7eeacb76db98156bdc8fa4cf9f618739add95f91a43259d70bbc618f1fd62d79b03d413a9e456f609598cb501e88",
          "sha256": "439b7d660db8f967194a38ef25277cb62741a54cce4440435cf7d52f2d512983",
          "sha1": "9ec4c2a5e28bf7b2d60e254e976940b12c8ba32a",
          "md5": "56071c2648d5e1da2796d84f30326a48"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-aop",
          "version": {
            "requires": "6.1.11"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-beans",
          "version": {
            "requires": "6.1.11"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-context",
          "version": {
            "requires": "6.1.11"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "6.1.11"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-expression",
          "version": {
            "requires": "6.1.11"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-web",
          "version": {
            "requires": "6.1.11"
          }
        }
      ],
      "files": [
        {
          "name": "spring-webmvc-6.1.11.jar",
          "url": "spring-webmvc-6.1.11.jar",
          "size": 1046877,
          "sha512": "610888d2b0ff8727594c51b5362fce5dec4f7eeacb76db98156bdc8fa4cf9f618739add95f91a43259d70bbc618f1fd62d79b03d413a9e456f609598cb501e88",
          "sha256": "439b7d660db8f967194a38ef25277cb62741a54cce4440435cf7d52f2d512983",
          "sha1": "9ec4c2a5e28bf7b2d60e254e976940b12c8ba32a",
          "md5": "56071c2648d5e1da2796d84f30326a48"
        }
      ]
    }
  ]
}
