server:
  servlet:
    encoding:
      force: 'true'
      enabled: 'true'
      charset: UTF-8

    context-path: /
  port: '8080'
spring:
  web:
  application:
    name: demo
  main:
    allow-bean-definition-overriding: true
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
