server:
  servlet:
    encoding:
      force: 'true'
      enabled: 'true'
      charset: UTF-8
    context-path: /
  port: '8080'
spring:
  web:
    resources:
      static-locations: classpath:/static/
  application:
    name: demo
  jpa:
    properties:
      hibernate:
        naming:
          physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    hibernate:
      ddl-auto: update
    show-sql: 'true'
  mvc:
    static-path-pattern: /static/

  datasource:
    password: 'Alswn1858!'
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://my-rds-instance.c7ooggw06nqt.ap-northeast-2.rds.amazonaws.com
  :3306/my_rds_name